name: Deploy my Lambda Function 
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: Ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      - name: Install libraries
        run: |
            cd funtion
            python -m pip install --upgrade pip
            if [ -f requirement.txt ]; then pip install -r requirements.txt -t.; fi
      - name: Create zip bundle
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
          
      
